In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/ashutoshpdy/Developer/GitHub Project (git clone)/MAA/MAA_Maternal-Awareness-Aid/mlops/data/raw/Maternal Health Risk Data Set.csv")
df.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          1014 non-null   int64
 1   SystolicBP   1014 non-null   int64
 2   DiastolicBP  1014 non-null   int64
 3   BS           1014 non-null   float64
 4   BodyTemp     1014 non-null   float64
 5   HeartRate    1014 non-null   int64
 6   RiskLevel    1014 non-null   object
dtypes: float64(2), int64(4), object(1)
memory usage: 55.6+ KB

,Age,SystolicBP,DiastolicBP,BS,BodyTemp,HeartRate
count,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000
mean,29.871795,113.198225,76.460552,8.725986,98.665089,74.301775
std,13.474386,18.403913,13.885796,3.293532,1.371384,8.088702
min,10.000000,70.000000,49.000000,6.000000,98.000000,7.000000
25%,19.000000,100.000000,65.000000,6.900000,98.000000,70.000000
50%,26.000000,120.000000,80.000000,7.500000,98.000000,76.000000
75%,39.000000,120.000000,90.000000,8.000000,98.000000,80.000000
max,70.000000,160.000000,100.000000,19.000000,103.000000,90.000000

In [4]:
df.columns = [
    "age",
    "systolic_bp",
    "diastolic_bp",
    "blood_sugar",
    "body_temp",
    "heart_rate",
    "risk_level"
]

In [8]:
df["risk_level"] = df["risk_level"].str.strip().str.lower()

In [9]:
df.groupby("risk_level").mean()

,age,systolic_bp,diastolic_bp,blood_sugar,body_temp,heart_rate,risk_score
risk_level,,,,,,,
high risk,36.216912,124.194853,85.073529,12.122610,98.899265,76.742647,2.0
low risk,26.869458,105.866995,72.534483,7.220271,98.368966,72.770936,0.0
mid risk,28.363095,113.154762,74.232143,7.795744,98.833333,74.175595,1.0

In [10]:
output_path = "/Users/ashutoshpdy/Developer/GitHub Project (git clone)/MAA/MAA_Maternal-Awareness-Aid/mlops/data/processed/Maternal Health Risk Data Set.csv"
df.to_csv(output_path, index=False)