In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("/Users/ashutoshpdy/Developer/GitHub Project (git clone)/MAA/MAA_Maternal-Awareness-Aid/mlops/data/raw/Dataset - Updated.csv")
df.head(5)

,Age,Systolic BP,Diastolic,BS,Body Temp,BMI,Previous Complications,Preexisting Diabetes,Gestational Diabetes,Mental Health,Heart Rate,Risk Level
0,22,90.0,60.0,9.0,100,18.0,1.0,1.0,0,1,80.0,High
1,22,110.0,70.0,7.1,98,20.4,0.0,0.0,0,0,74.0,Low
2,27,110.0,70.0,7.5,98,23.0,1.0,0.0,0,0,72.0,Low
3,20,100.0,70.0,7.2,98,21.2,0.0,0.0,0,0,74.0,Low
4,20,90.0,60.0,7.5,98,19.7,0.0,0.0,0,0,74.0,Low

In [5]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [6]:
df["risk_level"] = df["risk_level"].str.lower()

In [7]:
df["bmi"] = df["bmi"].fillna(df["bmi"].median())

In [8]:
binary_cols = [
    "previous_complications",
    "preexisting_diabetes",
    "gestational_diabetes",
    "mental_health"
]

In [10]:
df[binary_cols].isnull().sum()

previous_complications    2
preexisting_diabetes      2
gestational_diabetes      0
mental_health             0
dtype: int64

In [11]:
df[binary_cols] = df[binary_cols].fillna(0).astype(int)

In [12]:
df.head()

,age,systolic_bp,diastolic,bs,body_temp,bmi,previous_complications,preexisting_diabetes,gestational_diabetes,mental_health,heart_rate,risk_level
0,22,90.0,60.0,9.0,100,18.0,1,1,0,1,80.0,high
1,22,110.0,70.0,7.1,98,20.4,0,0,0,0,74.0,low
2,27,110.0,70.0,7.5,98,23.0,1,0,0,0,72.0,low
3,20,100.0,70.0,7.2,98,21.2,0,0,0,0,74.0,low
4,20,90.0,60.0,7.5,98,19.7,0,0,0,0,74.0,low

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age                     1205 non-null   int64
 1   systolic_bp             1200 non-null   float64
 2   diastolic               1201 non-null   float64
 3   bs                      1203 non-null   float64
 4   body_temp               1205 non-null   int64
 5   bmi                     1205 non-null   float64
 6   previous_complications  1205 non-null   int64
 7   preexisting_diabetes    1205 non-null   int64
 8   gestational_diabetes    1205 non-null   int64
 9   mental_health           1205 non-null   int64
 10  heart_rate              1203 non-null   float64
 11  risk_level              1187 non-null   object
dtypes: float64(5), int64(6), object(1)
memory usage: 113.1+ KB

In [14]:
df = df.dropna(subset=["risk_level"])

In [16]:
numeric_cols = [
    "systolic_bp",
    "diastolic",
    "bs",
    "heart_rate"
]

for col in numeric_cols:
    df[col].fillna(df[col].median(), inplace=True)

/var/folders/_l/dzdndlkd7p19xpwv8fcvn24c0000gn/T/ipykernel_95483/1076032488.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/var/folders/_l/dzdndlkd7p19xpwv8fcvn24c0000gn/T/ipykernel_95483/1076032488.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/var/folders/_l/dzdndlkd7p19xpwv8fcvn24c0000gn/T/ipykernel_95483/1076032488.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/var/folders/_l/dzdndlkd7p19xpwv8fcvn24c0000gn/T/ipykernel_95483/1076032488.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [17]:
df.isna().sum()

age                       0
systolic_bp               0
diastolic                 0
bs                        0
body_temp                 0
bmi                       0
previous_complications    0
preexisting_diabetes      0
gestational_diabetes      0
mental_health             0
heart_rate                0
risk_level                0
dtype: int64

In [18]:
output_path = "/Users/ashutoshpdy/Developer/GitHub Project (git clone)/MAA/MAA_Maternal-Awareness-Aid/mlops/data/processed/Maternal Health Risk Data Set1.csv"
df.to_csv(output_path, index=False)